#define _GNU_SOURCE
#include "crypto_support.h"

/* Public-API integration: also linked to the actual .so in shared builds.
 * The checked-in history was generated by the previous external backend.
 * No reference crypto library is linked or invoked by this test. */
static void copy_fixture(const char *dir, const char *name)
{
	char source[PATH_MAX];
	int n = snprintf(source, sizeof(source), "%s/%s", dir, name);
	CHECK(n > 0 && (size_t)n < sizeof(source));
	crypto_file_t saved = crypto_snapshot(source);
	crypto_restore(name, &saved);
	free(saved.data);
}

static void append_and_verify(audit_integrity_t algorithm)
{
	audit_config_t cfg = audit_test_config();
	cfg.integrity = algorithm;
	CHECK(audit_init(&cfg) == 0);
	audit_status_t status;
	CHECK(audit_get_status(&status) == 0);
	CHECK(status.state == AUDIT_STATE_RUNNING);
	audit_event_t event = audit_test_event("BUILTIN_ONLY");
	event.detail = "payload prev=inside hash=inside remains quoted";
	CHECK(audit_begin(&event) == 0);
	CHECK(audit_end(&event, AUDIT_SUCCESS, 0) == 0);
	CHECK(audit_shutdown_status() == 0);
	CHECK(audit_verify_file_with("app.audit.log", algorithm) == 0);
}

int main(int argc, char **argv)
{
	CHECK(argc == 3 || argc == 4);
	CHECK(!strcmp(audit_crypto_backend(), "builtin"));
	audit_integrity_t algorithm = crypto_algorithm(argv[2]);
	char directory[] = "/tmp/logger-builtin-only-XXXXXX";
	enter_temp(directory);
	/* Invalid external-crypto configuration must have no influence. */
	CHECK(setenv("OPENSSL_CONF", "/nonexistent/logger/no-crypto.conf", 1) ==
	      0);
	CHECK(setenv("OPENSSL_MODULES", "/nonexistent/logger/no-providers",
		     1) == 0);
	CHECK(setenv("OPENSSL_ENGINES", "/nonexistent/logger/no-engines", 1) ==
	      0);
	if (!strcmp(argv[1], "legacy")) {
		CHECK(argc == 4);
		copy_fixture(argv[3], "app.audit.log");
		copy_fixture(argv[3], "app.audit.state");
		crypto_file_t before = crypto_snapshot("app.audit.log");
		CHECK(audit_verify_file_with("app.audit.log", algorithm) == 0);
		append_and_verify(algorithm);
		crypto_file_t after = crypto_snapshot("app.audit.log");
		CHECK(after.size > before.size);
		CHECK(!memcmp(before.data, after.data, before.size));
		CHECK(count_event("AUDIT_START") == 2);
		CHECK(count_event("AUDIT_STOP") == 2);
		free(before.data);
		free(after.data);
	} else {
		CHECK(!strcmp(argv[1], "lifecycle"));
		append_and_verify(algorithm);
		append_and_verify(algorithm);
		CHECK(count_event("AUDIT_START") == 2);
		CHECK(count_event("BUILTIN_ONLY") == 4);
		CHECK(count_event("AUDIT_STOP") == 2);
	}
	audit_test_cleanup(directory);
	printf("builtin-only %s %s passed\n", argv[1], argv[2]);
	return 0;
}
